Users:
    Admin:
        Nicholas Wold:
            calnet: "969517"
            email: nicholas.wold@berkeley.edu
        Petr Brym:
            calnet: "1016937"
            email: petr.brym@berkeley.edu
    Standard:
        John Doe:
            calnet: "000001"
            email: nobody@odyssey.edu
